### ISSUE TITLE
Remove libupnp formula?

### ISSUE THREAD

**Issue by galliangg** [gerbera/homebrew-gerbera#23]
libupnp is included in Homebrew, is there a need for this formula?

brew info gerbera/gerbera/libupnp
gerbera/gerbera/libupnp: stable 1.8.6
The portable Universal Plug and Play (UPnP) SDK
https://github.com/pupnp/pupnp/
Not installed
From: https://github.com/gerbera/homebrew-gerbera/blob/HEAD/libupnp.rb
==> Dependencies
Build: autoconf ✘, automake ✘, libtool ✘
==> Options
--without-ipv6
	Disable IPv6 support
--without-reuseaddr
	Disable reuseaddr support

brew info libupnp                
libupnp: stable 1.14.0 (bottled)
Portable UPnP development kit
https://pupnp.sourceforge.io/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libupnp.rb
License: BSD-3-Clause

**Comment by whyman** [comment]
We should drop these for sure if they are not needed.

At the time, these packages where not available..
