### ISSUE TITLE
Remove duktape formula?

### ISSUE THREAD

**Issue by galliangg** [gerbera/homebrew-gerbera#24]
duktape is included in Homebrew, is there a need for this formula?

brew info gerbera/gerbera/duktape
gerbera/gerbera/duktape: stable 2.5.0
Embeddable Javascript engine with compact footprint
http://duktape.org
Not installed
From: https://github.com/gerbera/homebrew-gerbera/blob/HEAD/duktape.rb

brew info duktape                
duktape: stable 2.5.0 (bottled)
Embeddable Javascript engine with compact footprint
https://duktape.org
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/duktape.rb
License: MIT

**Comment by whyman** [comment]
We should drop these for sure if they are not needed.

At the time, these packages where not available..
